In [1]:
import pandas as pd
import numpy as np

In [4]:
#importing the dataset covid-19
df = pd.read_csv('COVID-19.csv')
df.head()

Sno  age  gender  body temperature  Dry Cough  sour throat  weakness  \
0    1   20       1              98.6          0            0         0   
1    2   19       1              99.0          1            0         0   
2    3   55       0             102.0          1            1         1   
3    4   40       0             100.0          0            0         0   
4    5   33       1              99.2          0            1         0   

   breathing problem  drowsiness  pain in chest  ...  diabetes  heart disease  \
0                  0           0              0  ...         0              0   
1                  0           0              0  ...         0              0   
2                  1           1              1  ...         0              0   
3                  0           1              1  ...         1              0   
4                  1           0              0  ...         0              0   

   lung disease  stroke or reduced immunity  symptoms progressed  \
0             0                           0                    0   
1             0                           0                    0   
2             0                           0                    0   
3             0                           0                    1   
4             1                           1                    1   

   high blood pressue  kidney disease  change in appetide  \
0                   0               0                   0   
1                   0               0                   0   
2                   0               0                   1   
3                   1               0                   1   
4                   0               0                   0   

   Loss of sense of smell  Corona result  
0                       0              0  
1                       0              0  
2                       0              1  
3                       0              2  
4                       1              2  

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 21 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Sno                                   127 non-null    int64  
 1   age                                   127 non-null    int64  
 2   gender                                127 non-null    int64  
 3   body temperature                      127 non-null    float64
 4   Dry Cough                             127 non-null    int64  
 5   sour throat                           127 non-null    int64  
 6   weakness                              127 non-null    int64  
 7   breathing problem                     127 non-null    int64  
 8   drowsiness                            127 non-null    int64  
 9   pain in chest                         127 non-null    int64  
 10  travel history to infected countries  127 non-null    int64  
 11  diabetes           

In [6]:
#categorizing the continuous variables age and temperature
bins= [0,10,20,55,100]
labels = ['Kids','Teen','Adult','Old Age']
Age = pd.cut(df['age'], bins=bins, labels=labels, right=False)
df["Age"]=Age
df=df.drop(['age'],axis=1)

bins= [96,98.6,102,110]
labels = ['normal','fever','high fever']
Temp = pd.cut(df['body temperature'], bins=bins, labels=labels, right=False)
df["Temp"]=Temp
df=df.drop(['body temperature'],axis=1)

df.head()

Sno  gender  Dry Cough  sour throat  weakness  breathing problem  \
0    1       1          0            0         0                  0   
1    2       1          1            0         0                  0   
2    3       0          1            1         1                  1   
3    4       0          0            0         0                  0   
4    5       1          0            1         0                  1   

   drowsiness  pain in chest  travel history to infected countries  diabetes  \
0           0              0                                     0         0   
1           0              0                                     0         0   
2           1              1                                     0         0   
3           1              1                                     1         1   
4           0              0                                     1         0   

   ...  lung disease  stroke or reduced immunity  symptoms progressed  \
0  ...             0                           0                    0   
1  ...             0                           0                    0   
2  ...             0                           0                    0   
3  ...             0                           0                    1   
4  ...             1                           1                    1   

   high blood pressue  kidney disease  change in appetide  \
0                   0               0                   0   
1                   0               0                   0   
2                   0               0                   1   
3                   1               0                   1   
4                   0               0                   0   

   Loss of sense of smell  Corona result      Age        Temp  
0                       0              0    Adult       fever  
1                       0              0     Teen       fever  
2                       0              1  Old Age  high fever  
3                       0              2    Adult       fever  
4                       1              2    Adult       fever  

[5 rows x 21 columns]

In [7]:
print(df['Age'].value_counts())
print(df['Temp'].value_counts())

Adult      104
Old Age     16
Teen         7
Kids         0
Name: Age, dtype: int64
fever         85
high fever    29
normal        13
Name: Temp, dtype: int64


In [8]:
#applying label encoding
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Age'] = le.fit_transform(df['Age'])
df['Temp'] = le.fit_transform(df['Temp'])

print(df['Age'].value_counts())
print(df['Temp'].value_counts())

0    104
1     16
2      7
Name: Age, dtype: int64
0    85
1    29
2    13
Name: Temp, dtype: int64


In [9]:
df.head()

Sno  gender  Dry Cough  sour throat  weakness  breathing problem  \
0    1       1          0            0         0                  0   
1    2       1          1            0         0                  0   
2    3       0          1            1         1                  1   
3    4       0          0            0         0                  0   
4    5       1          0            1         0                  1   

   drowsiness  pain in chest  travel history to infected countries  diabetes  \
0           0              0                                     0         0   
1           0              0                                     0         0   
2           1              1                                     0         0   
3           1              1                                     1         1   
4           0              0                                     1         0   

   ...  lung disease  stroke or reduced immunity  symptoms progressed  \
0  ...             0                           0                    0   
1  ...             0                           0                    0   
2  ...             0                           0                    0   
3  ...             0                           0                    1   
4  ...             1                           1                    1   

   high blood pressue  kidney disease  change in appetide  \
0                   0               0                   0   
1                   0               0                   0   
2                   0               0                   1   
3                   1               0                   1   
4                   0               0                   0   

   Loss of sense of smell  Corona result  Age  Temp  
0                       0              0    0     0  
1                       0              0    2     0  
2                       0              1    1     1  
3                       0              2    0     0  
4                       1              2    0     0  

[5 rows x 21 columns]

In [24]:
#splitting the inportant features to x and y

X =df.drop(['Corona result' , 'Sno' , 'heart disease','kidney disease' , 'change in appetide' , 'lung disease' , 'weakness' ] , axis=1)
y = df['Corona result']

In [39]:
#train and test split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , y , random_state = 1 , test_size = 0.20)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(101, 14)
(101,)
(26, 14)
(26,)


# Decision Tree 

In [40]:
from sklearn.tree import DecisionTreeClassifier  
model = DecisionTreeClassifier()  
model.fit(x_train, y_train)
DecisionTreeClassifier(class_weight=None,criterion='gini ',min_impurity_decrease=0.0,min_samples_leaf=1, min_samples_split=2,min_weight_fraction_leaf=0.0, presort=False, splitter='best')

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini ',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score
#accuracy for training data
print(accuracy_score(y_train,model.predict(x_train)))

0.9702970297029703


In [44]:
print(confusion_matrix(y_train,model.predict(x_train)))

[[26  0  0]
 [ 2 51  0]
 [ 0  1 21]]


In [45]:
#accuracy for testing data
print(accuracy_score(y_test,model.predict(x_test)))

0.7307692307692307


In [42]:
print(confusion_matrix(y_test,model.predict(x_test)))

[[ 6  1  0]
 [ 1 12  3]
 [ 1  1  1]]


# Random Forest 

In [168]:
from sklearn.ensemble import RandomForestClassifier

covid = RandomForestClassifier(min_samples_leaf=3 , max_features= 1 , random_state= 2)
covid.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=1,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=2, verbose=0,
                       warm_start=False)

In [169]:
#accuracy for training data
print(accuracy_score(y_train,covid.predict(x_train)))

0.7425742574257426


In [170]:
print(confusion_matrix(y_train,covid.predict(x_train)))

[[16 10  0]
 [ 1 52  0]
 [ 0 15  7]]


In [171]:
#accuracy for testing data
print(accuracy_score(y_test,covid.predict(x_test)))

0.7692307692307693
